const catalog = [
	{
		id: "neon",
		name: "Неон",
		image_path: "img/catalog/c1.avif",
		old_price: "120500 руб.",
		new_price: "55490 руб.",
	},
	{
		id: "standart",
		name: "Штандарт",
		image_path: "img/catalog/c2.avif",
		old_price: "112500 руб.",
		new_price: "56690 руб.",
	},
	{
		id: "dorry",
		name: "Дорри",
		image_path: "img/catalog/c3.avif",
		old_price: "84500 руб.",
		new_price: "33690 руб.",
	},
	{
		id: "savanna",
		name: "Саванна",
		image_path: "img/catalog/c4.avif",
		old_price: "80200 руб.",
		new_price: "31890 руб.",
	},
	{
		id: "scarlett",
		name: "Скарлетт",
		image_path: "img/catalog/c5.avif",
		old_price: "89400 руб.",
		new_price: "42600 руб.",
	},
	{
		id: "shale",
		name: "Шале",
		image_path: "img/catalog/c6.avif",
		old_price: "83500 руб.",
		new_price: "40200 руб.",
	},
	{
		id: "victoria",
		name: "Виктория",
		image_path: "img/catalog/c7.avif",
		old_price: "94800 руб.",
		new_price: "57790 руб.",
	},
	{
		id: "melange",
		name: "Меланж",
		image_path: "img/catalog/c8.avif",
		old_price: "88300 руб.",
		new_price: "42600 руб.",
	},
	{
		id: "rosinka",
		name: "Росинка",
		image_path: "img/catalog/c9.avif",
		old_price: "94200 руб.",
		new_price: "50690 руб.",
	},
	{
		id: "vector",
		name: "Вектор",
		image_path: "img/catalog/c10.avif",
		old_price: "97390 руб.",
		new_price: "54600 руб.",
	},
	{
		id: "classic",
		name: "Классик",
		image_path: "img/catalog/c11.avif",
		old_price: "103500 руб.",
		new_price: "62090 руб.",
	},
	{
		id: "lira",
		name: "Лира",
		image_path: "img/catalog/c12.avif",
		old_price: "99390 руб.",
		new_price: "55900 руб.",
	},
]